title: "By learning to do the easy things the hard way, the hard things will become easy" 
subtitle: Royale and Dorazio
author:
  name: ManuBaz
  twitter_username: MBazzichetto
  email: manuele.bazzichetto@gmail.com
  github: ManueleBazzichetto
 
production_url: https://manuelebazzichetto.github.io/pers-website

#setup 
markdown: kramdown

plugins:
  - jemoji
  - jekyll-relative-links
 
relattive_links:
  enabled: true
  collections: true

include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
