title: "By learning to do the easy things the hard way, the hard things will become easy" Royale and Dorazio

production_url: https://manuelebazzichetto.github.io/pers-website

#setup 
markdown: kramdown

plugins:
  - jemoji

theme: jekyll-theme-cayman
