show_downloads: true
darkmode: true
hide_first_title: true
colors:
    gradient_left: "#FF3333"
    gradient_right: "#DAC0C0"
    header: "#000000"
    android_theme: "#000"
    link: "#1e6bb8"
    section_title: "#155799"

production_url: https://manuelebazzichetto.github.io/pers-website

#setup 
markdown: kramdown

plugins:
  - jemoji

theme: jekyll-theme-cayman
remote_theme: tuur29/pages-themes-cayman

github:
  home_url: https://manuelebazzichetto.github.io/pers-website 
  cv_url: https://manuelebazzichetto.github.io/pers-website/CV
  pics_url: https://manuelebazzichetto.github.io/pers-website/PicsFromField
  blog_url: https://manuelebazzichetto.github.io/pers-website/Blog
