author:
  name: ManuBaz
  twitter_username: MBazzichetto
  email: manuele.bazzichetto@gmail.com
  github: ManueleBazzichetto
 
production_url: https://manuelebazzichetto.github.io/pers-website

#setup 
markdown: kramdown

