title: "By learning to do the easy things the hard way, the hard things will become easy"
tagline: Royal & Dorazio
author:
  name: ManuBaz
  twitter_username: MBazzichetto
  email: manuele.bazzichetto@gmail.com
  github: ManueleBazzichetto
 
production_url: https://manuelebazzichetto.github.io/pers-website

#setup 
markdown: kramdown

