show_downloads: true
darkmode: true
hide_first_title: true

production_url: https://manuelebazzichetto.github.io/pers-website

#setup 
markdown: kramdown

plugins:
  - jemoji

theme: jekyll-theme-cayman
remote_theme: tuur29/pages-themes-cayman

github:
  home_url: https://manuelebazzichetto.github.io/pers-website 
  cv_url: https://manuelebazzichetto.github.io/pers-website/CV
  pics_url: https://manuelebazzichetto.github.io/pers-website/PicsFromField
  blog_url: https://manuelebazzichetto.github.io/pers-website/Blog
