show_downloads: true

production_url: https://manuelebazzichetto.github.io/pers-website

#setup 
markdown: kramdown

plugins:
  - jemoji

theme: jekyll-theme-cayman

github:
  home_url: https://manuelebazzichetto.github.io/pers-website 
  cv_url: https://manuelebazzichetto.github.io/pers-website/CV
  pics_url: https://manuelebazzichetto.github.io/pers-website/PicsFromField
