title: "By learning to do the easy things the hard way, the hard things will become easy"
description: Royale & Dorazio

show_downloads: true

production_url: https://manuelebazzichetto.github.io/pers-website

#setup 
markdown: kramdown

plugins:
  - jemoji

theme: jekyll-theme-cayman

github:
  zip_url: https://github.com/ManueleBazzichetto/pers-website
  another_url: https://manuelebazzichetto.github.io/pers-website/CV
